#**Random Forest**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_excel("Dataset_set_2.xlsx")

#**C-class Flares**

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 38].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
y_train=np.asarray(y_train,dtype=int)

In [0]:
from sklearn import ensemble
regressor = ensemble.RandomForestClassifier(max_depth=None, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1561,   89],
       [ 457, 1245]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.95      0.85      1650
           1       0.93      0.73      0.82      1702

    accuracy                           0.84      3352
   macro avg       0.85      0.84      0.84      3352
weighted avg       0.85      0.84      0.84      3352



#**M-class Flares**

Without using C-class flares data

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 39].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
y_train=np.asarray(y_train,dtype=int)

In [0]:
from sklearn import ensemble
regressor = ensemble.RandomForestClassifier(max_depth=None, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[2833,   25],
       [ 442,   52]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.99      0.92      2858
           1       0.68      0.11      0.18       494

    accuracy                           0.86      3352
   macro avg       0.77      0.55      0.55      3352
weighted avg       0.84      0.86      0.81      3352



Using C-class flares data

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 39].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
y_train=np.asarray(y_train,dtype=int)

In [0]:
from sklearn import ensemble
regressor = ensemble.RandomForestClassifier(max_depth=None, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[2839,   19],
       [ 444,   50]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92      2858
           1       0.72      0.10      0.18       494

    accuracy                           0.86      3352
   macro avg       0.79      0.55      0.55      3352
weighted avg       0.84      0.86      0.81      3352



#**X-class flares**

Without using C-class and M-class flares data

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
y_train=np.asarray(y_train,dtype=int)

In [0]:
from sklearn import ensemble
regressor = ensemble.RandomForestClassifier(max_depth=None, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:          #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1647,    1],
       [  27,    1]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.50      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.74      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



Using C-class flares data

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
y_train = np.asarray(y_train,dtype=int)

In [0]:
from sklearn import ensemble
regressor = ensemble.RandomForestClassifier(max_depth=None, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:              #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1648,    0],
       [  27,    1]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       1.00      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.99      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



Using C-class and M-class flares data

In [0]:
X = dataset.iloc[1:, 0:40].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)#Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
y_train=np.asarray(y_train,dtype=int)

In [0]:
from sklearn import ensemble
regressor = ensemble.RandomForestClassifier(max_depth=None, random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:              #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1647,    1],
       [  28,    0]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.00      0.00      0.00        28

    accuracy                           0.98      1676
   macro avg       0.49      0.50      0.50      1676
weighted avg       0.97      0.98      0.97      1676

