#**SVR (rbf kernel)**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_excel("Dataset_set_2.xlsx")

#For c-class solar flares

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 38].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1439,  211],
       [ 255, 1447]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.87      0.86      1650
           1       0.87      0.85      0.86      1702

    accuracy                           0.86      3352
   macro avg       0.86      0.86      0.86      3352
weighted avg       0.86      0.86      0.86      3352



# For m-class Solar flares

**Not using the data of c-class flares**

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 39].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[2840,   18],
       [ 437,   57]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

'''
High precision and low recall means 
FalseNegatives = High
FalsePositives = Low
'''

              precision    recall  f1-score   support

           0       0.87      0.99      0.93      2858
           1       0.76      0.12      0.20       494

    accuracy                           0.86      3352
   macro avg       0.81      0.55      0.56      3352
weighted avg       0.85      0.86      0.82      3352



**Using the data of c-class solar flares**

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 39].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[2836,   22],
       [ 436,   58]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.87      0.99      0.93      2858
           1       0.72      0.12      0.20       494

    accuracy                           0.86      3352
   macro avg       0.80      0.55      0.56      3352
weighted avg       0.85      0.86      0.82      3352



#For X-class flares

**Not using c-class & m-class flares data**

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)    #Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:          #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1647,    1],
       [  27,    1]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.50      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.74      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



**Using c-class flares data**

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)    #Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:              #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1648,    0],
       [  28,    0]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.00      0.00      0.00        28

    accuracy                           0.98      1676
   macro avg       0.49      0.50      0.50      1676
weighted avg       0.97      0.98      0.98      1676



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


**Using c-class and m-class flares data**

In [0]:
X = dataset.iloc[1:, 0:40].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)    #Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)
#y_train = sc_y_train.fit_transform(y_train)
#y_test = sc_y_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:                #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1647,    1],
       [  27,    1]])

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.50      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.74      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676

