#**SVR (Polynomial kernel)**

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
dataset = pd.read_excel("Dataset_set_2.xlsx")

#**C-class Flares**

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 38].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1384,  266],
       [ 269, 1433]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.84      0.84      0.84      1650
           1       0.84      0.84      0.84      1702

    accuracy                           0.84      3352
   macro avg       0.84      0.84      0.84      3352
weighted avg       0.84      0.84      0.84      3352



#**M-class Flares**

Without using C-class flares data

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 39].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[2835,   23],
       [ 443,   51]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.99      0.92      2858
           1       0.69      0.10      0.18       494

    accuracy                           0.86      3352
   macro avg       0.78      0.55      0.55      3352
weighted avg       0.84      0.86      0.81      3352



Using C-class flares data

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 39].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=1:
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[2830,   28],
       [ 441,   53]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.99      0.92      2858
           1       0.65      0.11      0.18       494

    accuracy                           0.86      3352
   macro avg       0.76      0.55      0.55      3352
weighted avg       0.83      0.86      0.81      3352



#**X-class flares**

Without using C-class and M-class flares data

In [0]:
X = dataset.iloc[1:, 0:38].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:          #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1642,    6],
       [  26,    2]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.25      0.07      0.11        28

    accuracy                           0.98      1676
   macro avg       0.62      0.53      0.55      1676
weighted avg       0.97      0.98      0.98      1676



Using C-class flares data

In [0]:
X = dataset.iloc[1:, 0:39].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) #Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:              #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1647,    1],
       [  27,    1]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.50      0.04      0.07        28

    accuracy                           0.98      1676
   macro avg       0.74      0.52      0.53      1676
weighted avg       0.98      0.98      0.98      1676



Using C-class and M-class flares data

In [0]:
X = dataset.iloc[1:, 0:40].values
y = dataset.iloc[1:, 40].values

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)#Changing the train:test to 80:20

In [0]:
from sklearn.preprocessing import StandardScaler
sc_X_train = StandardScaler()
sc_y_train = StandardScaler()
X_train = sc_X_train.fit_transform(X_train)
X_test = sc_X_train.transform(X_test)

In [0]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'poly')
regressor.fit(X_train, y_train)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='poly', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [0]:
y_pred = regressor.predict(X_test)
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
for i in range(0,len(y_pred)):
  if y_pred[i]>=0.5:              #threshold value for y_pred is decreased to 0.5
    y_pred[i]=1
  else:
    y_pred[i]=0
  if y_test[i]>=1:
    y_test[i]=1
  else:
    y_test[i]=0

In [0]:
y_test=np.asarray(y_test,dtype=int)
y_pred=np.asarray(y_pred,dtype=int)

In [0]:
from sklearn.metrics import confusion_matrix
cm_1 = confusion_matrix(y_test, y_pred)
cm_1

array([[1647,    1],
       [  28,    0]], dtype=int64)

In [0]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99      1648
           1       0.00      0.00      0.00        28

    accuracy                           0.98      1676
   macro avg       0.49      0.50      0.50      1676
weighted avg       0.97      0.98      0.97      1676

